// PDF Export utility - Using browser print functionality
export const exportToPDF = (data, type) => {
  // Create a printable HTML document
  const printWindow = window.open('', '_blank');
  
  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>Smart Calculator Report</title>
      <style>
        body {
          font-family: Arial, sans-serif;
          margin: 40px;
          color: #333;
        }
        .header {
          text-align: center;
          color: #667eea;
          border-bottom: 2px solid #667eea;
          padding-bottom: 20px;
          margin-bottom: 30px;
        }
        .section {
          margin-bottom: 25px;
        }
        .section h2 {
          color: #667eea;
          margin-bottom: 15px;
        }
        .detail-row {
          display: flex;
          justify-content: space-between;
          margin-bottom: 10px;
          padding: 8px 0;
          border-bottom: 1px solid #eee;
        }
        .label {
          font-weight: bold;
          color: #495057;
        }
        .value {
          font-weight: bold;
          color: #667eea;
        }
        .footer {
          margin-top: 40px;
          text-align: center;
          color: #6c757d;
          font-size: 12px;
          border-top: 1px solid #eee;
          padding-top: 20px;
        }
        @media print {
          body { margin: 20px; }
          .no-print { display: none; }
        }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>Smart Calculator Report</h1>
        <p>Generated on: ${new Date().toLocaleString()}</p>
        <p>Calculation Type: ${type === 'interest' ? 'Interest Calculation' : 'EMI Calculation'}</p>
      </div>
      
      <div class="section">
        <h2>${type === 'interest' ? 'Interest Calculation Results' : 'EMI Calculation Results'}</h2>
        ${type === 'interest' ? `
          <div class="detail-row">
            <span class="label">Principal Amount:</span>
            <span class="value">₹${data.principal.toLocaleString()}</span>
          </div>
          <div class="detail-row">
            <span class="label">Interest Earned:</span>
            <span class="value">₹${parseFloat(data.interest).toLocaleString()}</span>
          </div>
          <div class="detail-row">
            <span class="label">Total Amount:</span>
            <span class="value">₹${parseFloat(data.amount).toLocaleString()}</span>
          </div>
          <div class="detail-row">
            <span class="label">Calculation Type:</span>
            <span class="value">${data.calculationType.charAt(0).toUpperCase() + data.calculationType.slice(1)} Interest</span>
          </div>
          <div class="detail-row">
            <span class="label">Interest Frequency:</span>
            <span class="value">${data.interestType.charAt(0).toUpperCase() + data.interestType.slice(1)}</span>
          </div>
        ` : `
          <div class="detail-row">
            <span class="label">Loan Amount:</span>
            <span class="value">₹${data.principal.toLocaleString()}</span>
          </div>
          <div class="detail-row">
            <span class="label">Monthly EMI:</span>
            <span class="value">₹${parseFloat(data.emi).toLocaleString()}</span>
          </div>
          <div class="detail-row">
            <span class="label">Total Interest:</span>
            <span class="value">₹${parseFloat(data.totalInterest).toLocaleString()}</span>
          </div>
          <div class="detail-row">
            <span class="label">Total Amount:</span>
            <span class="value">₹${parseFloat(data.totalAmount).toLocaleString()}</span>
          </div>
          <div class="detail-row">
            <span class="label">Number of Payments:</span>
            <span class="value">${data.numberOfPayments}</span>
          </div>
        `}
      </div>
      
      ${type === 'emi' ? `
        <div class="section">
          <h2>Payment Breakdown</h2>
          <div class="detail-row">
            <span class="label">Principal Percentage:</span>
            <span class="value">${((data.principal / parseFloat(data.totalAmount)) * 100).toFixed(1)}%</span>
          </div>
          <div class="detail-row">
            <span class="label">Interest Percentage:</span>
            <span class="value">${((parseFloat(data.totalInterest) / parseFloat(data.totalAmount)) * 100).toFixed(1)}%</span>
          </div>
        </div>
      ` : ''}
      
      <div class="footer">
        <p>Generated by Smart Calculator</p>
        <p>This report was created on ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}</p>
      </div>
      
      <div class="no-print" style="text-align: center; margin-top: 30px;">
        <button onclick="window.print()" style="padding: 10px 20px; background: #667eea; color: white; border: none; border-radius: 5px; cursor: pointer;">
          Print Report
        </button>
        <button onclick="window.close()" style="padding: 10px 20px; background: #6c757d; color: white; border: none; border-radius: 5px; cursor: pointer; margin-left: 10px;">
          Close
        </button>
      </div>
    </body>
    </html>
  `;
  
  printWindow.document.write(htmlContent);
  printWindow.document.close();
  
  // Auto-print after a short delay
  setTimeout(() => {
    printWindow.print();
  }, 500);
};
